# Generated by Django 4.2.5 on 2023-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approval_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
