# Generated by Django 4.2.7 on 2023-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_author_blogpost_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='body_1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_6',
            field=models.TextField(blank=True),
        ),
    ]
