# Generated by Django 4.2.7 on 2023-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('body_2', models.TextField()),
                ('body_3', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('thumb', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
    ]
