# Generated by Django 4.2.7 on 2023-11-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='body_3',
        ),
        migrations.AlterField(
            model_name='about',
            name='body_2',
            field=models.TextField(blank=True),
        ),
    ]
