# Generated by Django 4.2.7 on 2023-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_body_3_alter_about_body_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='body_2',
            new_name='additional_body',
        ),
        migrations.AlterField(
            model_name='about',
            name='technology',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
