# Generated by Django 4.2.7 on 2023-11-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
