# Generated by Django 4.2.7 on 2023-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile',
            field=models.CharField(max_length=200),
        ),
    ]
