# Generated by Django 4.2.7 on 2023-11-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_about_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='about',
            name='technology2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='technology3',
        ),
    ]
