# Generated by Django 4.2.7 on 2023-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_about_technology_remove_about_technology2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact_body',
            field=models.TextField(blank=True),
        ),
    ]
